import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ToastProvider from "@/components/toast/ToastProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CineScope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>
          {children}
        </ToastProvider>

        <style
          dangerouslySetInnerHTML={{
            __html: `
              :root {
                --toast-offset: 80px;
              }

              @media (max-width: 640px) {
                :root {
                  --toast-offset: 90px;
                }
              }

              /* Keep the toaster pinned to the right on mobile */
              @media (max-width: 640px) {
                [data-sonner-toaster] {
                  right: 12px !important;
                  left: auto !important;
                }
              }
            `,
          }}
        />
      </body>
    </html>
  );
}